title: "cal's blog - "
description: "site description for seo"
baseurl: "/"
url: "https://calware.github.io"

header_pages:
  - index.md
  - about.md
  - contact.md

style: dark

footer: ''

# Build settings
markdown: kramdown
remote_theme: calware/blog
