title: "calware - "
description: "A Blog about Reverse Engineering and Binary Deobfuscation"
baseurl: "/"
url: "https://calwa.re"

google_analytics: UA-145145815-1

header_pages:
  - index.md
  - about.md
  - contact.md

style: dark

footer: ''

plugins:
  - jekyll-sitemap
  - jekyll-feed

# Build settings
markdown: kramdown
remote_theme: calware/blog
