title: "cal's blog - "
description: "thoughtful blog"
baseurl: "/"
url: "http://calwa.re"

header_pages:
  - index.md
  - about.md
  - contact.md

style: dark

footer: ''

# Build settings
markdown: kramdown
remote_theme: calware/blog
