title: "calware - "
description: "Calware: A Blog about Reverse Engineering and Binary Obfuscation/Deobfuscation"
baseurl: "/"
url: "https://calwa.re"

google_analytics: UA-145145815-1

header_pages:
  - index.md
  - downloads.md
  - about.md
  - contact.md

style: dark

footer: '<a href="https://github.com/calware" target="_blank">Check out my Github</a>'

plugins:
  - jekyll-sitemap
  - jekyll-feed

# Build settings
markdown: kramdown
remote_theme: calware/blog

permalink: /:categories/:title
