title: ""
description: "reverse engineering"
baseurl: "/"
url: "https://calwa.re"

header_pages:
  - index.md
  - about.md
  - contact.md

style: dark

footer: ''

# Build settings
markdown: kramdown
remote_theme: calware/blog
