title: "cal's blog - "
description: "thoughtful blog"
baseurl: "/blog"
url: "https://calware.github.io"

header_pages:
  - index.md
  - about.md
  - contact.md

style: dark

footer: ''

# Build settings
markdown: kramdown
remote_theme: calware/blog
