# Example Site settings

#header_pages:
#  - index.md
#  - about.md

#footer: 'follow us on <a href="https://twitter.com/">twitter</a>'

#style: light # dark (default) or light

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
